

\documentclass{article}
\usepackage{graphics}
\usepackage{rotating}
\usepackage{hyperref}
\begin{document}



  \title{Evaluating NMF Results}
  \author{Peter Castaldi}
  \maketitle
  \tableofcontents

<<init,echo=F>>=

library(xtable)
library(cluster)
library(psych)
library(reshape)
options(stringsAsFactors=F)
dat<-"/udd/repjc/RESEARCH/DATA/COPDGENE/"
source("/udd/repjc/RESEARCH/CLUSTERING/ClustFuncsVer1.R")

@  


Here we take results from Yale sent on June 1, 2014. 

<<data,echo=F>>=

eclPheno<-read.table(paste("/proj/regeps/regep00/studies/ECLIPSE/data/biomarker/2013_GSK_Biomarker_Data/PJC/silverman_07oct13_SubjectDataTab.txt",sep=""),header=T,stringsAsFactors=F,sep="\t")

## select and normalize some attributes and create NMF axes - preFEV1pp, emphysema, ratio, upper third, pi10, fvc, tlc: TLC has high missingness
keepVars<-c("Global.Subject.ID","Age.in.years","Sex","Percent.predicted.post.BD.FEV1","Post.BD.FEV.FVC....","Exacerbations..Year.prior.to.Screening","FracVol...950HU.","Body.mass.index..kg.m2.","Number.of.pack.years.smoked","GOLD.Stage.code","Subject.group","Neutrophils..10.9.L.","Lymphocytes..10.9.L.","Monocytes..10.9.L.","Eosinophils..10.9.L.")
  
pheno<-eclPheno[,keepVars]
pheno$sid<-paste("EC",pheno$Global.Subject.ID,sep="")
pheno<-pheno[,-1]
names(pheno)[3]<-c("FEV1pp_utah")

#truncate exacerbations
pheno$Exacerbations..Year.prior.to.Screening[pheno$Exacerbations..Year.prior.to.Screening>2]<-3

#Read in genotype data
gdata4<-read.table("/udd/repjc/RESEARCH/CLUSTERING/ECLIPSE_CHR4_GWSSNPs_May2014.raw",header=T,as.is=TRUE) 
gdata15<-read.table("/udd/repjc/RESEARCH/CLUSTERING/ECLIPSE_CHR15_GWSSNPs_May2014.raw",header=T,as.is=TRUE) 
gdata19<-read.table("/udd/repjc/RESEARCH/CLUSTERING/ECLIPSE_CHR19_GWSSNPs_May2014.raw",header=T,as.is=TRUE) 

gdata<-merge(gdata4[,c(1,7,8)],gdata15[,c(1,7,8)],by="FID")
gdata<-merge(gdata,gdata19[,c(1,7)])

names(gdata)[1]<-"sid"

genesall<-merge(pheno[pheno$sid %in% gdata$sid,],gdata,by="sid")

#Read in clusters
nmfcoef<-read.csv("/udd/repjc/RESEARCH/NBS/NMF_norm_LF4/NMF_norm_LF4_coef.csv",header=F)
ids<-read.table("/udd/repjc/RESEARCH/NBS/NMF_norm_LF4/patient_id.txt",header=F)
names(nmfcoef)<-ids$V1

cat("\nTake a peek at the NMF H matrix.")
nmfcoef[,1:6]

hmat<-as.data.frame(t(nmfcoef))
names(hmat)<-paste("L",1:4,sep="")
hmat$sid<-paste("EC",rownames(hmat),sep="")

#merge with pheno data
hmp<-merge(hmat,pheno,by="sid")
cat("\nCorrelations between latent factors and COPD-related measures.")

for(a in c("L1","L2","L3","L4")){
  cat("\n********************",a)
  form<-as.formula(paste(a,"~FEV1pp_utah",sep=""))
  x<-glm(form,data=hmp)
  cat("\n")
  print(summary(x)$coefficients)

  form<-as.formula(paste(a,"~FracVol...950HU.",sep=""))
  x<-glm(form,data=hmp)
  cat("\n")
  print(summary(x)$coefficients)

  form<-as.formula(paste(a,"~Exacerbations..Year.prior.to.Screening",sep=""))
  x<-glm(form,data=hmp)
  cat("\n")
  print(summary(x)$coefficients)

  form<-as.formula(paste(a,"~Number.of.pack.years.smoked",sep=""))
  x<-glm(form,data=hmp)
  cat("\n")
  print(summary(x)$coefficients)

  form<-as.formula(paste(a,"~Subject.group",sep=""))
  x<-glm(form,data=hmp)
  cat("\n")
  print(summary(x)$coefficients)
}


#cluster on the H matrix
hmp$cluster<-"NA"
for(a in 1:nrow(hmp)){
  hmp[a,"cluster"]<-which.max(hmp[a,c("L1","L2","L3","L4")])
}
table(hmp$cluster)

nbslf4<-data.frame("sid"=hmp$sid,"nbslf4"=hmp$cluster)

nbslf4all<-merge(nbslf4,pheno,by="sid")

@ 


\clearpage


<<defineassessmentfunction,echo=F,results=tex>>=

makeassoc<-function(ccsall,ccssome,cdf,gdata,clusvar,SD="N",k,lambda,printtab=FALSE){   #ccsall = dataframe with all clinical data + cluster results, ccssome = dataframe with clinical characteristics for printout, cdf = dataframe with cluster results and sid only, gdata = dataframe with additively coded genotypes and sids, clusvar = name of cluster variable (vector with all cluster assignments), k = number of clusters, lambda = lambda for cc algorithm
  if(min(table(cdf[,clusvar]))<5 | length(table(cdf[,clusvar]))<k ) {   # This chunk prevents the ANOVA from failing when one cluster size is too small
    aovout<-vector()
    for(a in 1:5){
      aovout[a]<-1
    }
  } else {
    char<-cluscharsd(ccsall[,c("sid",clusvar)],bdata=ccssome,clusvar=clusvar,SD=SD)
    ref<-names(char)[2*which.max(char["FEV1pp_utah",seq(2,ncol(char),2)])]   # get the number of the cluster with best FEV1, this will be reference
    ref<-strsplit(ref,":")[[1]][1]
    ref<-strsplit(ref,"C")[[1]][2]
    if(printtab) print(xtable(char,caption=paste("Results for k=",k,", lambda=",lambda,sep=""),digits=c(0,(rep(c(0,2),ncol(char)/2)))),floating.environment="sidewaystable")  
    gd<-merge(ccssome,gdata,by="sid")
    gd<-merge(gd,cdf[,c("sid",clusvar)])                  
    x<-snpglm(gd,snps=c(names(gdata)[-1]),ref=ref,cname=clusvar,a=k,rowname=TRUE,adjust=NULL)
    if(printtab) t<-snpORPrint(snpres=x,k=k,ref=ref,tables=NULL,file=NULL,print=TRUE)
    aovout<-vector()
    for(a in names(gdata)[-1]){
      aovout[a]<-summary(aov(gd[,a]~as.factor(gd[,clusvar])))[[1]][[5]][1]
    }
  }
 aovout
}


@ 

\section{NBSLF4 Cluster Results}


<<random,results=tex,echo=F>>=

  a<-makeassoc(nbslf4all,nbslf4all[,-c(2,4,12)],nbslf4,gdata,clusvar="nbslf4",k=4,lambda=0,printtab=T)

@ 

\clearpage

<<anova,echo=F>>=

  cat("\nANOVA association results for k=4 :")
  a
  
@ 


\clearpage

\section{Predictive Value of Clusters}

Quantify the incremental predictive value of NMF-derived clusters above and beyond traditional covariates.

<<increment,echo=F>>=
require(ordinal)
hmp$cluster<-as.factor(hmp$cluster)
hmp$Exacerbations..Year.prior.to.Screening<-as.factor(hmp$Exacerbations..Year.prior.to.Screening)

  cat("\n********************")
  cat("\nFEV1:")
  x<-glm(FEV1pp_utah~Age.in.years+Sex+Number.of.pack.years.smoked+cluster,data=hmp)
  cat("\n")
  print(summary(x)$coefficients)

  cat("\nFracVol...950HU.:")
  x<-glm(FracVol...950HU.~Age.in.years+Sex+Number.of.pack.years.smoked+cluster,data=hmp)
  cat("\n")
  print(summary(x)$coefficients)

  cat("\nExacerbations:")
  x<-clm(Exacerbations..Year.prior.to.Screening~Age.in.years+Sex+Number.of.pack.years.smoked+cluster,data=hmp)
  cat("\n")
  print(summary(x)$coefficients)

  cat("\nPack-Years:")
  x<-glm(Number.of.pack.years.smoked~Age.in.years+Sex+FracVol...950HU.+FEV1pp_utah+cluster,data=hmp)
  cat("\n")
  print(summary(x)$coefficients)


@ 

\clearpage

Quantify the incremental predictive value of NMF-derived clusters above and beyond traditional covariates, including cell count (neutrophils,lymphocytes,monocytes, and eosinophils.


<<incrementcbc,echo=F>>=

  cat("\n********************")
  cat("\nFEV1:")
  x<-glm(FEV1pp_utah~Age.in.years+Sex+Number.of.pack.years.smoked+Neutrophils..10.9.L.+Lymphocytes..10.9.L.+Monocytes..10.9.L.+Eosinophils..10.9.L.+cluster,data=hmp)
  cat("\n")
  print(summary(x)$coefficients)

cat("\nFracVol...950HU.:")
  x<-glm(FracVol...950HU.~Age.in.years+Sex+Number.of.pack.years.smoked+Neutrophils..10.9.L.+Lymphocytes..10.9.L.+Monocytes..10.9.L.+Eosinophils..10.9.L.+cluster,data=hmp)
  cat("\n")
  print(summary(x)$coefficients)

cat("\nExacerbations:")                                                                                                                
  x<-clm(Exacerbations..Year.prior.to.Screening~Age.in.years+Sex+Number.of.pack.years.smoked+Neutrophils..10.9.L.+Lymphocytes..10.9.L.+Monocytes..10.9.L.+Eosinophils..10.9.L.+cluster,data=hmp)
  cat("\n")
  print(summary(x)$coefficients)

cat("Pack=Years:")                                                                                                                      
  x<-glm(Number.of.pack.years.smoked~Age.in.years+Sex+FracVol...950HU.+FEV1pp_utah+Neutrophils..10.9.L.+Lymphocytes..10.9.L.+Monocytes..10.9.L.+Eosinophils..10.9.L.+cluster,data=hmp)
  cat("\n")
  print(summary(x)$coefficients)

  
@ 

\end{document}
